language: cpp

os: linux
dist: trusty
sudo: required
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt53base qt53x11extras
  - source /opt/qt53/bin/qt53-env.sh

script:
  - mkdir build
  - cd build
  - qmake ../HiDPI-Fixer.pro
  - make -j$(nproc)

notifications:
  email: false
